name: Mocha CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build leap-mock
        run: npm run build

      - name: Run tests
        env:
          LOG_LEVEL: debug
        run: npm run test